"""
labels.py — Transparency label generation.

The label is the one thing a non-technical reader actually sees. There are
exactly three variants, chosen by the attribution verdict. Each one:
  - states the result in plain language,
  - turns the raw confidence into a percentage a layperson can read,
  - is honest that this is an automated estimate, not a verdict, and
  - (for the AI case) points the creator to the appeal path.

The verbatim templates below are reproduced in the README.
"""


def _pct(confidence):
    return f"{round(confidence * 100)}%"


def make_label(attribution, confidence):
    """Return a dict with the headline + body text for the given verdict."""
    pct = _pct(confidence)

    if attribution == "likely_ai":
        return {
            "variant": "high_confidence_ai",
            "headline": "🤖 Likely AI-generated",
            "body": (
                f"Our automated analysis estimates this content was probably "
                f"created with the help of generative AI (confidence: {pct}). "
                f"This is an estimate, not a certainty — AI detection is an "
                f"unsolved problem. If you are the creator and believe this is "
                f"wrong, you can appeal and a human will review it."
            ),
        }

    if attribution == "likely_human":
        return {
            "variant": "high_confidence_human",
            "headline": "✍️ Likely human-written",
            "body": (
                f"Our automated analysis found no strong signs of AI generation "
                f"in this content (confidence: {pct}). This is an estimate, not "
                f"a guarantee of authorship."
            ),
        }

    # uncertain
    return {
        "variant": "uncertain",
        "headline": "❓ Attribution uncertain",
        "body": (
            f"Our automated analysis could not confidently determine whether "
            f"this content was written by a human or generated by AI "
            f"(confidence in either direction: {pct}). Rather than guess, we are "
            f"telling you honestly: treat the origin as unverified."
        ),
    }
